### PR TITLE
upped baro to int32_t  to keep from overflowing

### PR DESCRIPTION
**Pull request by superjax**
The barometer is in Pa, so 101 kPa is outside the range of a 16 bit integer.

### CODE REVIEW

**Review by dpkoch — COMMENTED** [review]
@superjax Do you think we might ever try to pull request our changes to get our custom messages included in the official repo? If not then deleting the extra files may be okay. If there is a possibility though, I think it'd be best to keep our changes as minimal as possible. Thoughts?

**Comment by dpkoch** [comment]
Also, should we just do the conversion onboard and send it over mavlink as a floating point value instead of an int?

**Comment by superjax** [comment]
I don't know.  I guess it makes sense if we intend on using the altitude data.  Here is the conversion

``` c
alt = (1.0f - pow(pressure/101325.0f, 0.190284f)) * 0.304 * 145366.45f; // in meters
```

I don't love the idea of doing a `pow()` all the time, though, we probably don't need to worry too much.

I haven't actually though about trying to pull into the main repo.  I'm not opposed to it, but I figured that we weren't too interested in that.  I guess it makes sense to have it maintained by those guys if they are willing to do it.

What's your opinion?

**Comment by superjax** [comment]
I would like to have actual baro pressure data in addition to altitude though, so I think we should keep the message regardless.  That conversion doesn't use temperature, and I could imagine us one day including temperature measurements for better modeling on the ROS side.

**Pull request closed without merging**
